export const SET_SEARCH = "SET_SEARCH";
export const SET_ADVANCE_SEARCH = "SET_ADVANCE_SEARCH";
export const SET_FILTERS = "SET_FILTERS";
export const SET_FILTERS_VALUE = "SET_FILTERS_VALUE";
export const SET_NEWS = "SET_NEWS";
export const SET_SELECTED_NEWS = "SET_SELECTED_NEWS"
